// 🌙 잠자리 동화 모음
// - 각 이야기(story)는 여러 장면(scene)으로 나뉜다.
// - story.voice: 누가 읽어주는지 표시용. "엄마" 또는 "아빠". 값이 없으면 자동 음성으로 봄.
//                (이야기 하나는 통째로 한 사람이 녹음. 카드에 배지로 보여준다)
// - scene.art  : 화면에 크게 보여줄 이모지 그림
// - scene.text : 읽어줄 글 (자동 음성이 이 글을 읽는다)
// - scene.audio: 녹음한 음성 파일 경로. 값을 넣으면 자동 음성 대신 그 파일을 재생한다.
//                예) audio: "assets/stories/heungbu/heungbu-01.m4a"

export const STORIES = [
  {
    id: "heungbu",
    title: "흥부와 놀부",
    kind: "전래동화",
    emoji: "🐦",
    voice: "엄마",
    // 엄마가 직접 녹음한 목소리로 읽어 준다 (파일이 없으면 자동 음성으로 대체)
    scenes: [
      { art: "🏡🌾", audio: "assets/stories/heungbu/heungbu-01.m4a", text: "옛날 옛날 아주 먼 옛날에, 흥부와 놀부 형제가 살았어요. 동생 흥부는 마음씨가 아주 따뜻했고, 형 놀부는 욕심이 많았답니다." },
      { art: "🐦🎶", audio: "assets/stories/heungbu/heungbu-02.m4a", text: "어느 봄날, 흥부네 집 처마 밑에 제비 가족이 둥지를 틀었어요. 지지배배, 지지배배. 아기 제비들이 노래를 불렀지요." },
      { art: "🐣🤲", audio: "assets/stories/heungbu/heungbu-03.m4a", text: "그런데 어느 날, 아기 제비 한 마리가 그만 둥지에서 툭 떨어지고 말았어요. 아이고, 아가야, 많이 아팠겠구나. 흥부는 아기 제비의 다친 다리를 고운 천으로 살살 감아 주었어요." },
      { art: "🐦🍂", audio: "assets/stories/heungbu/heungbu-04.m4a", text: "정성껏 돌봐 준 덕분에 아기 제비는 씩씩하게 나았어요. 가을이 되자 제비는, 고마웠어요 흥부 아저씨, 인사하고 따뜻한 남쪽 나라로 날아갔답니다." },
      { art: "🐦🌱", audio: "assets/stories/heungbu/heungbu-05.m4a", text: "다음 해 봄, 제비가 다시 찾아왔어요. 입에는 조그만 박씨 하나를 물고 있었지요. 흥부 아저씨, 이건 고마움의 선물이에요." },
      { art: "🏡🎃", audio: "assets/stories/heungbu/heungbu-06.m4a", text: "흥부네 가족은 박씨를 심고 물을 주었어요. 박은 무럭무럭 자라서, 지붕 위에 둥근 박이 주렁주렁 열렸답니다." },
      { art: "✨💰", audio: "assets/stories/heungbu/heungbu-07.m4a", text: "영차, 영차, 슬근슬근 톱질하세. 흥부네 가족이 박을 타자, 세상에! 박 속에서 쌀이랑 보물이랑 예쁜 옷이 가득가득 나왔어요." },
      { art: "🤗🍚", audio: "assets/stories/heungbu/heungbu-08.m4a", text: "흥부네 가족은 부자가 되었어요. 하지만 흥부는 변하지 않고, 이웃들과 사이좋게 나누며 지냈답니다." },
      { art: "😠🐦", audio: "assets/stories/heungbu/heungbu-09.m4a", text: "그 소식을 들은 놀부는 심술이 났어요. 일부러 제비 다리를 다치게 하고는 대충 감아 주었지요. 그건 착한 일이 아니었어요." },
      { art: "👹🎃", audio: "assets/stories/heungbu/heungbu-10.m4a", text: "놀부네 박에서는 보물 대신 도깨비들이 나와서 놀부를 혼내 주었어요. 욕심쟁이 놀부야, 이제 그러면 안 돼!" },
      { art: "🥲🫂", audio: "assets/stories/heungbu/heungbu-11.m4a", text: "놀부는 엉엉 울며 잘못했다고 말했어요. 마음씨 착한 흥부는 형을 꼭 안아 주었지요. 형님, 우리 이제 사이좋게 지내요." },
      { art: "🌙💤", audio: "assets/stories/heungbu/heungbu-12.m4a", text: "그 뒤로 흥부와 놀부는 오래오래 행복하게 살았답니다. 착한 마음은 언제나 복을 가져다준대요. 우리 긴주도 따뜻한 꿈 꾸자. 잘 자요." },
    ],
  },
  {
    id: "ginjoo-moon",
    title: "긴주와 달님 이불",
    kind: "창작동화",
    emoji: "🌙",
    voice: "엄마",
    // 이 이야기는 엄마가 직접 녹음한 목소리로 읽어 준다 (파일이 없으면 자동 음성으로 대체)
    scenes: [
      { art: "🌃⭐", audio: "assets/stories/dalnim/dalnim-01.m4a", text: "밤이 되었어요. 하늘이 까만 이불을 덮고, 별들이 하나둘 눈을 떴어요. 긴주도 이제 코 잘 시간이에요." },
      { art: "👶🪟", audio: "assets/stories/dalnim/dalnim-02.m4a", text: "그런데 달님이 보이지 않네요? 긴주는 창밖을 보며 말했어요. 달님, 어디 있어요?" },
      { art: "🌙☁️", audio: "assets/stories/dalnim/dalnim-03.m4a", text: "그때 구름 뒤에서 달님이 빼꼼 얼굴을 내밀었어요. 긴주야, 안녕. 나 여기 있어. 잘 시간이 되어서 인사하러 왔지." },
      { art: "🌙🛏️", audio: "assets/stories/dalnim/dalnim-04.m4a", text: "달님은 은은한 달빛으로 긴주의 방을 포근하게 비춰 주었어요. 달빛은 보들보들, 꼭 부드러운 이불 같았지요." },
      { art: "😊💕", audio: "assets/stories/dalnim/dalnim-05.m4a", text: "긴주야, 오늘 하루 재미있었니? 긴주는 고개를 끄덕끄덕. 맘마도 먹고, 놀이도 하고, 엄마랑 뽀뽀도 했어요." },
      { art: "👋🌙", audio: "assets/stories/dalnim/dalnim-06.m4a", text: "그럼 이제 잘 자는 인사를 해 볼까? 달님이 속삭였어요. 긴주는 조그만 손을 흔들었어요." },
      { art: "🧸😴", audio: "assets/stories/dalnim/dalnim-07.m4a", text: "잘 자, 곰돌이 인형아. 곰돌이도 꾸벅꾸벅 졸고 있네요. 잘 자, 까까야. 내일 또 만나." },
      { art: "👟🪟", audio: "assets/stories/dalnim/dalnim-08.m4a", text: "잘 자, 신발아. 오늘 많이 걸었지? 신발도 현관에서 나란히 코 자요. 잘 자, 창문아. 잘 자, 불빛아." },
      { art: "🌙🎵", audio: "assets/stories/dalnim/dalnim-09.m4a", text: "달님이 노래를 불러 주었어요. 자장자장 우리 긴주, 꼬까신도 잠이 들고, 곰돌이도 잠이 들고, 우리 긴주도 코 자지요." },
      { art: "😴🛏️", audio: "assets/stories/dalnim/dalnim-10.m4a", text: "긴주의 눈이 스르르 감겨요. 달님이 달빛 이불을 살포시 덮어 주었어요. 포근포근, 따뜻따뜻." },
      { art: "☁️🍪", audio: "assets/stories/dalnim/dalnim-11.m4a", text: "긴주야, 꿈나라에서 만나자. 꿈나라에는 맛있는 까까 나무랑, 폭신폭신 구름 미끄럼틀이 있단다." },
      { art: "🌙💤", audio: "assets/stories/dalnim/dalnim-12.m4a", text: "별들도 소곤소곤, 달님도 방긋방긋. 잘 자, 우리 긴주. 사랑해. 엄마도 아빠도 긴주를 사랑해요. 코, 잘 자요." },
    ],
  },
  {
    id: "baby-star",
    title: "잘 자, 아기 별",
    kind: "창작동화",
    emoji: "⭐",
    voice: "아빠",
    scenes: [
      { art: "🌌⭐", audio: "assets/stories/byeol/byeol-01.m4a", text: "어느 날 밤, 하늘 나라에서 조그만 아기 별이 반짝반짝 놀고 있었어요. 아기 별은 잠자기가 싫었대요. 더 놀고 싶은걸!" },
      { art: "🌟😮", audio: "assets/stories/byeol/byeol-02.m4a", text: "엄마 별이 말했어요. 아가야, 별도 코 자야 아침에 해님이 나올 수 있단다. 그래도 아기 별은 도리도리, 눈을 말똥말똥 떴어요." },
      { art: "💫🪟", audio: "assets/stories/byeol/byeol-03.m4a", text: "아기 별은 폴짝폴짝 뛰다가 그만 미끄러져서, 하늘에서 스르르 미끄러져 내려왔어요. 그리고 사뿐, 긴주네 창가에 내려앉았지요." },
      { art: "👶✨", audio: "assets/stories/byeol/byeol-04.m4a", text: "여기가 어디지? 아기 별이 두리번두리번. 그때 긴주가 아기 별을 보았어요. 어? 반짝반짝 아기 별이네!" },
      { art: "⭐🙏", audio: "assets/stories/byeol/byeol-05.m4a", text: "아기 별이 말했어요. 난 잠자기가 싫어서 도망 왔어. 나랑 놀자! 하지만 긴주는 알고 있었어요. 밤은 코 자는 시간이라는 걸요." },
      { art: "🧸🤫", audio: "assets/stories/byeol/byeol-06.m4a", text: "긴주가 아기 별에게 보여 주었어요. 봐, 곰돌이도 자고 있어. 쉬, 조용조용. 곰돌이는 쌔근쌔근 자고 있었지요." },
      { art: "🐶🌸", audio: "assets/stories/byeol/byeol-07.m4a", text: "강아지도 코 자고, 새들도 둥지에서 코 자고, 꽃들도 꽃잎을 오므리고 코 자. 아기 별은 깜짝 놀랐어요. 정말이네, 다들 자고 있구나." },
      { art: "⭐🥱", audio: "assets/stories/byeol/byeol-08.m4a", text: "그때 아기 별이 하품을 했어요. 하아암. 폴짝폴짝 뛰었더니, 아기 별도 사실은 졸렸던 거예요." },
      { art: "🛏️⭐", audio: "assets/stories/byeol/byeol-09.m4a", text: "긴주는 아기 별을 폭신한 베개 옆에 뉘어 주었어요. 그리고 이불을 살살 덮어 주었지요. 잘 자, 아기 별아." },
      { art: "🌟💕", audio: "assets/stories/byeol/byeol-10.m4a", text: "하늘에서 엄마 별이 내려다보며 방긋 웃었어요. 우리 아기, 착한 긴주가 재워 주는구나. 고마워, 긴주야." },
      { art: "😴☁️", audio: "assets/stories/byeol/byeol-11.m4a", text: "아기 별은 쌔근쌔근, 긴주도 스르르. 둘은 나란히 꿈나라로 떠났어요. 꿈속에서 둘이 구름 그네를 타고 놀았대요." },
      { art: "🌙💤", audio: "assets/stories/byeol/byeol-12.m4a", text: "아침이 되자 아기 별은 엄마 별 품으로 돌아갔어요. 그리고 밤마다 긴주네 창가에 반짝, 잘 자 인사를 보낸답니다. 잘 자, 우리 긴주." },
    ],
  },
  {
    id: "three-bears",
    title: "곰 세 마리",
    kind: "세계명작",
    emoji: "🐻",
    voice: "엄마",
    scenes: [
      { art: "🏡🌲", audio: "assets/stories/gom/gom-01.m4a", text: "깊고 깊은 숲속 작은 오두막에, 곰 세 마리 가족이 살았어요. 커다란 아빠 곰, 다정한 엄마 곰, 그리고 조그만 아기 곰이었지요." },
      { art: "🍲🐻", audio: "assets/stories/gom/gom-02.m4a", text: "어느 아침, 엄마 곰이 따뜻한 죽을 끓였어요. 큰 그릇에는 아빠 곰 죽, 중간 그릇에는 엄마 곰 죽, 작은 그릇에는 아기 곰 죽." },
      { art: "♨️🚶", audio: "assets/stories/gom/gom-03.m4a", text: "그런데 죽이 너무 뜨거웠어요. 후후, 식을 때까지 숲을 한 바퀴 산책하고 오자. 곰 세 마리는 손을 잡고 밖으로 나갔답니다." },
      { art: "👧🚪", audio: "assets/stories/gom/gom-04.m4a", text: "그때 금발머리 여자아이가 숲을 걷다가 오두막을 발견했어요. 똑똑, 계세요? 아무도 없네? 아이는 살그머니 안으로 들어갔지요." },
      { art: "🥣😋", audio: "assets/stories/gom/gom-05.m4a", text: "맛있는 죽 냄새! 아빠 곰 죽은 너무 뜨거워, 엄마 곰 죽은 너무 차가워, 아기 곰 죽은 딱 좋아! 아이는 아기 곰 죽을 후루룩 다 먹었어요." },
      { art: "🪑💥", audio: "assets/stories/gom/gom-06.m4a", text: "이번엔 의자 세 개. 아빠 의자는 너무 딱딱해, 엄마 의자는 너무 푹신해, 아기 의자는 딱 좋아! 그런데 그만, 아기 의자가 뚝 부서졌어요. 아이고." },
      { art: "🛏️😴", audio: "assets/stories/gom/gom-07.m4a", text: "슬슬 졸린 아이는 위층으로 올라갔어요. 아빠 침대는 너무 딱딱해, 엄마 침대는 너무 푹신해, 아기 침대는 딱 좋아! 아이는 새근새근 잠들었답니다." },
      { art: "🐻🐻🐻", audio: "assets/stories/gom/gom-08.m4a", text: "그때 곰 세 마리가 산책에서 돌아왔어요. 어라? 누가 내 죽을 먹었지? 누가 내 의자에 앉았지? 아기 곰이 두리번두리번." },
      { art: "😮🛏️", audio: "assets/stories/gom/gom-09.m4a", text: "위층으로 살금살금 올라가 보니, 세상에! 아기 곰 침대에 낯선 아이가 쌔근쌔근 자고 있지 뭐예요." },
      { art: "👧🙇", audio: "assets/stories/gom/gom-10.m4a", text: "인기척에 눈을 뜬 아이는 깜짝 놀랐어요. 미안해요, 허락도 없이 들어와서. 아이는 꾸벅 인사하고 집으로 돌아갔답니다." },
      { art: "🐻💛", audio: "assets/stories/gom/gom-11.m4a", text: "곰 세 마리는 화내지 않고 손을 흔들어 주었어요. 잘 가, 조심히 가렴. 그리고 다시 오순도순, 새 의자도 뚝딱 고쳤지요." },
      { art: "🌙💤", audio: "assets/stories/gom/gom-12.m4a", text: "아기 곰은 딱 맞는 자기 침대에 포근히 누웠어요. 새근새근, 숲도 조용조용. 우리 긴주도 딱 맞는 포근한 이불 덮고 코 자자. 잘 자요." },
    ],
  },
  {
    id: "ginjoo-animals",
    title: "긴주와 잠꾸러기 동물 친구들",
    kind: "창작동화",
    emoji: "🧸",
    voice: "엄마",
    scenes: [
      { art: "🌙👶", audio: "assets/stories/dongmul/dongmul-01.m4a", text: "밤이 깊었어요. 긴주가 코 잘 시간이에요. 그런데 동물 친구들이 아직도 말똥말똥, 잠이 안 오나 봐요." },
      { art: "🐻🥱", audio: "assets/stories/dongmul/dongmul-02.m4a", text: "곰돌이가 어슬렁어슬렁 왔어요. 하아암, 졸린데 잠이 안 와. 긴주가 이불을 살살 덮어 주었어요. 잘 자, 곰돌이." },
      { art: "🐰🤫", audio: "assets/stories/dongmul/dongmul-03.m4a", text: "아기 토끼가 깡충깡충. 난 아직 더 놀고 싶은걸! 긴주가 토닥토닥. 쉬, 이제 코 잘 시간이야. 토끼도 눈을 감았어요." },
      { art: "🐶💤", audio: "assets/stories/dongmul/dongmul-04.m4a", text: "강아지가 멍, 긴주 곁에 폭 안겼어요. 긴주가 부드럽게 쓰다듬어 주었지요. 잘 자, 강아지. 강아지도 쌔근쌔근." },
      { art: "🐤🪺", audio: "assets/stories/dongmul/dongmul-05.m4a", text: "아기 새가 짹짹, 둥지에서 긴주를 불렀어요. 긴주야, 나도 재워 줘. 긴주가 자장자장 노래해 주자 아기 새도 스르르." },
      { art: "🐱🧶", audio: "assets/stories/dongmul/dongmul-06.m4a", text: "아기 고양이가 야옹, 동그랗게 몸을 말았어요. 긴주가 포근한 담요를 덮어 주었어요. 잘 자, 고양이야. 야옹, 고마워." },
      { art: "🐻🐰🐶", audio: "assets/stories/dongmul/dongmul-07.m4a", text: "동물 친구들이 모두 새근새근 잠들었어요. 긴주는 뿌듯했어요. 친구들 다 재웠다, 히히." },
      { art: "👶🥱", audio: "assets/stories/dongmul/dongmul-08.m4a", text: "그런데 긴주도 그만 하아암, 하품이 났어요. 어? 긴주도 사실은 많이 졸렸나 봐요." },
      { art: "🐻💗", audio: "assets/stories/dongmul/dongmul-09.m4a", text: "곰돌이가 눈을 살짝 뜨고 말했어요. 긴주야, 이제 네 차례야. 착한 긴주도 코 자야지." },
      { art: "🛏️🌙", audio: "assets/stories/dongmul/dongmul-10.m4a", text: "긴주는 폭신폭신한 이불 속으로 쏙 들어갔어요. 동물 친구들이 긴주 곁에 옹기종기 모여 폭 감싸 주었지요." },
      { art: "🌙😊", audio: "assets/stories/dongmul/dongmul-11.m4a", text: "달님이 창밖에서 방긋 웃었어요. 친구들을 다 재워 준 우리 긴주, 정말 착하구나. 이제 긴주도 잘 자렴." },
      { art: "😴💤", audio: "assets/stories/dongmul/dongmul-12.m4a", text: "동물 친구들도, 긴주도 나란히 새근새근 꿈나라로 떠났어요. 잘 자, 우리 긴주. 사랑해. 포근한 꿈 꾸자." },
    ],
  },
  {
    id: "tortoise-hare",
    title: "토끼와 거북이",
    kind: "이솝우화",
    emoji: "🐢",
    voice: "아빠",
    scenes: [
      { art: "🐰🐢", audio: "assets/stories/tokki/tokki-01.m4a", text: "옛날 어느 숲속에, 아주 빠른 토끼와 아주 느린 거북이가 살았어요. 토끼는 늘 자랑했지요. 내가 세상에서 제일 빨라!" },
      { art: "😤🐢", audio: "assets/stories/tokki/tokki-02.m4a", text: "느림보 거북아, 넌 언제 그렇게 엉금엉금 다니니? 토끼가 놀렸어요. 거북이는 속상했지만, 씩씩하게 웃었답니다." },
      { art: "🏁🤝", audio: "assets/stories/tokki/tokki-03.m4a", text: "그럼 우리, 저 언덕까지 달리기 시합할까? 거북이가 말했어요. 토끼는 깔깔 웃었어요. 좋아! 넌 절대로 날 못 이겨." },
      { art: "🐿️🐦", audio: "assets/stories/tokki/tokki-04.m4a", text: "숲속 친구들이 모여들었어요. 다람쥐도, 새들도 두근두근. 준비, 땅! 시합이 시작되었어요." },
      { art: "💨🐰", audio: "assets/stories/tokki/tokki-05.m4a", text: "토끼는 쌩쌩 바람처럼 달렸어요. 순식간에 저 멀리! 거북이는 엉금엉금, 한 걸음 또 한 걸음, 천천히 나아갔지요." },
      { art: "🌳😌", audio: "assets/stories/tokki/tokki-06.m4a", text: "한참 앞서간 토끼가 뒤를 돌아봤어요. 거북이는 보이지도 않네? 에이, 잠깐 쉬었다 가도 되겠다. 토끼는 시원한 나무 그늘에 누웠어요." },
      { art: "😴💤", audio: "assets/stories/tokki/tokki-07.m4a", text: "솔솔 부는 바람에 토끼는 그만 스르르 잠이 들었어요. 쿨쿨, 새근새근. 아주 깊이 잠들어 버렸지요." },
      { art: "🐢✨", audio: "assets/stories/tokki/tokki-08.m4a", text: "그동안 거북이는 쉬지 않았어요. 힘들어도 포기하지 않고, 엉금엉금 한 걸음씩 계속 나아갔답니다." },
      { art: "🐢🤫", audio: "assets/stories/tokki/tokki-09.m4a", text: "거북이는 쿨쿨 자는 토끼를 살금살금 지나쳤어요. 쉿, 조용조용. 토끼는 그것도 모르고 쿨쿨." },
      { art: "😱🐰", audio: "assets/stories/tokki/tokki-10.m4a", text: "한참 뒤에 토끼가 번쩍 눈을 떴어요. 어? 해가 뉘엿뉘엿. 앗, 큰일 났다! 토끼는 부리나케 달리기 시작했어요." },
      { art: "🎉🐢", audio: "assets/stories/tokki/tokki-11.m4a", text: "하지만 이미 늦었어요. 거북이가 먼저 언덕에 도착했지요! 와아, 거북이가 이겼다! 친구들이 손뼉을 쳤어요." },
      { art: "🌙💤", audio: "assets/stories/tokki/tokki-12.m4a", text: "거북이가 방긋 웃었어요. 천천히라도 끝까지 하면 되는 거야. 토끼도 고개를 끄덕이며 사이좋은 친구가 되었답니다. 우리 긴주도 천천히, 포근하게, 코 자자. 잘 자요." },
    ],
  },
];
